/** Industry package @amg-webui/onvif — opt-in; never imported by core */
/** AUTO-GENERATED by scripts/generate-entry.mjs — do not hand-edit */
export { default as OnvifAlarmPanel } from './OnvifAlarmPanel'
export { default as OnvifChannelManage } from './OnvifChannelManage'
export { default as OnvifDeviceList } from './OnvifDeviceList'
export { default as OnvifGroupTree } from './OnvifGroupTree'
export { default as OnvifRecordPlan } from './OnvifRecordPlan'
export { default as OnvifSearch } from './OnvifSearch'
export { default as OnvifSettingPanel } from './OnvifSettingPanel'
export { default as OnvifUrlForm } from './OnvifUrlForm'
