/**
 * Example zone → base component names (synced with packages/components/base).
 * Regenerated by: node scripts/sync-example-zones.mjs
 * Maturity: node scripts/score-component-maturity.mjs → component-maturity.json
 */
import zones from './component-zones.json'
import maturity from './component-maturity.json'

export type ExampleZoneId =
  | 'atoms'
  | 'forms'
  | 'data'
  | 'feedback'
  | 'layout'
  | 'third'
  | 'industry'
  | 'all'

export type MaturityLevel = 'stub' | 'shell' | 'beta' | 'ready'

export const COMPONENT_ZONES = zones as Record<Exclude<ExampleZoneId, 'all'>, string[]>

export const MATURITY_LEVELS = (maturity.levels ?? [
  'stub',
  'shell',
  'beta',
  'ready'
]) as MaturityLevel[]

export const MATURITY_SUMMARY = maturity.summary as Record<MaturityLevel, number>

export function zoneNames(zone: ExampleZoneId): string[] {
  if (zone === 'all') {
    return Object.values(COMPONENT_ZONES)
      .flat()
      .sort((a, b) => a.localeCompare(b))
  }
  return [...(COMPONENT_ZONES[zone] || [])].sort((a, b) => a.localeCompare(b))
}

export function componentMaturity(name: string): {
  level: MaturityLevel
  score: number
} {
  const row = (maturity.components as Record<string, { level?: MaturityLevel; score?: number }>)[
    name
  ]
  return {
    level: row?.level ?? 'shell',
    score: typeof row?.score === 'number' ? row.score : 0
  }
}

export function zoneMaturitySummary(zone: ExampleZoneId): Record<MaturityLevel, number> {
  const names = zoneNames(zone)
  const out: Record<MaturityLevel, number> = { stub: 0, shell: 0, beta: 0, ready: 0 }
  for (const n of names) {
    out[componentMaturity(n).level] += 1
  }
  return out
}
