import { defineConfig } from 'vitepress'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { packageAlias } from '../../build/shared.mjs'

const repoRoot = resolve(fileURLToPath(new URL('../..', import.meta.url)))

const viteAliases = Object.entries(packageAlias)
  .sort(([a], [b]) => b.length - a.length)
  .map(([find, replacement]) => ({ find, replacement }))

export default defineConfig({
  title: 'AMG-WebUI',
  description: 'Enterprise Vue Web Application UI Platform',
  vite: {
    resolve: {
      alias: viteAliases
    },
    ssr: {
      noExternal: [/^@amg-webui(\/|$)/, 'amg-webui']
    }
  },
  // Outside-docs SSOT paths + engineering pointers; dead-link strictness would fail the build.
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: '指南', link: '/guide/installation' },
      { text: '组件', link: '/components/' },
      { text: '主题', link: '/theme/' },
      { text: 'Skill Runtime', link: '/SKILL_RUNTIME' },
      { text: '业务模块', link: '/business/' }
    ],
    sidebar: [
      {
        text: '起步',
        items: [
          { text: '简介', link: '/' },
          { text: '安装', link: '/guide/installation' },
          { text: '快速开始', link: '/guide/quick-start' },
          { text: '0.1 发布说明', link: '/RELEASE_0.1' },
          { text: '0.1 组件子集', link: '/V0_1_SUBSET' }
        ]
      },
      {
        text: '独家能力',
        items: [
          { text: 'Skill Runtime', link: '/SKILL_RUNTIME' },
          { text: 'Vp Telemetry', link: '/TELEMETRY' },
          { text: '安全防护层', link: '/SECURITY' },
          { text: '低代码 Schema', link: '/LOWCODE' }
        ]
      },
      {
        text: '主题',
        items: [
          { text: '主题体系', link: '/theme/' },
          { text: 'Theme Studio', link: '/THEME_STUDIO' }
        ]
      },
      {
        text: '业务模块',
        items: [{ text: '概览', link: '/business/' }]
      },
      {
        text: '组件（v0.1 核心）',
        items: [
          { text: '概览', link: '/components/' },
          { text: 'Button', link: '/components/button' },
          { text: 'Select', link: '/components/select' },
          { text: 'DataTable', link: '/components/data-table' },
          { text: 'Tree', link: '/components/tree' },
          { text: 'Form', link: '/components/form' },
          { text: 'Dialog', link: '/components/dialog' },
          { text: 'InputText', link: '/components/input-text' },
          { text: 'Checkbox', link: '/components/checkbox' },
          { text: 'Switch', link: '/components/switch' },
          { text: 'Pagination', link: '/components/pagination' },
          { text: 'Layout', link: '/components/layout' },
          { text: 'Menu', link: '/components/menu' },
          { text: 'Tabs', link: '/components/tabs' },
          { text: 'Alert', link: '/components/alert' },
          { text: 'MessageBox', link: '/components/message-box' },
          { text: 'ConfigProvider', link: '/components/config-provider' },
          { text: 'Segmented', link: '/components/segmented' },
          { text: 'Affix', link: '/components/affix' },
          { text: 'Image', link: '/components/image' },
          { text: 'Tour', link: '/components/tour' },
          { text: '—— Stable ——', link: '/components/' },
          { text: 'AdvancedSearch ★', link: '/components/advanced-search' },
          { text: 'Anchor ★', link: '/components/anchor' },
          { text: 'AudioPlay ★', link: '/components/audio-play' },
          { text: 'AudioTalk ★', link: '/components/audio-talk' },
          { text: 'AutoComplete ★', link: '/components/auto-complete' },
          { text: 'Avatar ★', link: '/components/avatar' },
          { text: 'AvatarGroup ★', link: '/components/avatar-group' },
          { text: 'BackTop ★', link: '/components/back-top' },
          { text: 'Badge ★', link: '/components/badge' },
          { text: 'BarChart ★', link: '/components/bar-chart' },
          { text: 'Barcode ★', link: '/components/barcode' },
          { text: 'BatchPanel ★', link: '/components/batch-panel' },
          { text: 'BatchUpload ★', link: '/components/batch-upload' },
          { text: 'Block ★', link: '/components/block' },
          { text: 'Breadcrumb ★', link: '/components/breadcrumb' },
          { text: 'BreadcrumbItem ★', link: '/components/breadcrumb-item' },
          { text: 'BrowserDetect ★', link: '/components/browser-detect' },
          { text: 'Business404 ★', link: '/components/business404' },
          { text: 'ButtonGroup ★', link: '/components/button-group' },
          { text: 'Calendar ★', link: '/components/calendar' },
          { text: 'CanvasIo ★', link: '/components/canvas-io' },
          { text: 'CanvasLayer ★', link: '/components/canvas-layer' },
          { text: 'CanvasNode ★', link: '/components/canvas-node' },
          { text: 'CanvasPreview ★', link: '/components/canvas-preview' },
          { text: 'CanvasShortcut ★', link: '/components/canvas-shortcut' },
          { text: 'Card ★', link: '/components/card' },
          { text: 'CardGrid ★', link: '/components/card-grid' },
          { text: 'CardList ★', link: '/components/card-list' },
          { text: 'CardNav ★', link: '/components/card-nav' },
          { text: 'CardWidgets ★', link: '/components/card-widgets' },
          { text: 'Carousel ★', link: '/components/carousel' },
          { text: 'Cartoon404 ★', link: '/components/cartoon404' },
          { text: 'Cascader ★', link: '/components/cascader' },
          { text: 'CategoryNav ★', link: '/components/category-nav' },
          { text: 'Center ★', link: '/components/center' },
          { text: 'CheckboxGroup ★', link: '/components/checkbox-group' },
          { text: 'ChunkUpload ★', link: '/components/chunk-upload' },
          { text: 'Clipboard ★', link: '/components/clipboard' },
          { text: 'CodeEditor ★', link: '/components/code-editor' },
          { text: 'Col ★', link: '/components/col' },
          { text: 'Collapse ★', link: '/components/collapse' },
          { text: 'ColorInput ★', link: '/components/color-input' },
          { text: 'ColorPicker ★', link: '/components/color-picker' },
          { text: 'ColumnLayout ★', link: '/components/column-layout' },
          { text: 'Confirm ★', link: '/components/confirm' },
          { text: 'ConfirmDialog ★', link: '/components/confirm-dialog' },
          { text: 'Container ★', link: '/components/container' },
          { text: 'ContextMenu ★', link: '/components/context-menu' },
          { text: 'CopyText ★', link: '/components/copy-text' },
          { text: 'Countdown ★', link: '/components/countdown' },
          { text: 'CryptoBox ★', link: '/components/crypto-box' },
          { text: 'Dashboard ★', link: '/components/dashboard' },
          { text: 'DataCard ★', link: '/components/data-card' },
          { text: 'DatePicker ★', link: '/components/date-picker' },
          { text: 'DateTimePicker ★', link: '/components/date-time-picker' },
          { text: 'Descriptions ★', link: '/components/descriptions' },
          { text: 'DescriptionsItem ★', link: '/components/descriptions-item' },
          { text: 'DetailPanel ★', link: '/components/detail-panel' },
          { text: 'Divider ★', link: '/components/divider' },
          { text: 'Doodle404 ★', link: '/components/doodle404' },
          { text: 'DragCanvas ★', link: '/components/drag-canvas' },
          { text: 'DragMaterial ★', link: '/components/drag-material' },
          { text: 'DragRuler ★', link: '/components/drag-ruler' },
          { text: 'DragSelect ★', link: '/components/drag-select' },
          { text: 'DragSortNode ★', link: '/components/drag-sort-node' },
          { text: 'DragVerify ★', link: '/components/drag-verify' },
          { text: 'DragWrapper ★', link: '/components/drag-wrapper' },
          { text: 'Drawer ★', link: '/components/drawer' },
          { text: 'DrillTable ★', link: '/components/drill-table' },
          { text: 'Dropdown ★', link: '/components/dropdown' },
          { text: 'DynamicForm ★', link: '/components/dynamic-form' },
          { text: 'EditTable ★', link: '/components/edit-table' },
          { text: 'EditTree ★', link: '/components/edit-tree' },
          { text: 'Ellipsis ★', link: '/components/ellipsis' },
          { text: 'EmbedLayout ★', link: '/components/embed-layout' },
          { text: 'Empty ★', link: '/components/empty' },
          { text: 'ErrorModal ★', link: '/components/error-modal' },
          { text: 'ExcelIo ★', link: '/components/excel-io' },
          { text: 'Exception ★', link: '/components/exception' },
          { text: 'FilePreview ★', link: '/components/file-preview' },
          { text: 'FilterBar ★', link: '/components/filter-bar' },
          { text: 'FixedLayout ★', link: '/components/fixed-layout' },
          { text: 'FloatButton ★', link: '/components/float-button' },
          { text: 'FloatNav ★', link: '/components/float-nav' },
          { text: 'FlowLayout ★', link: '/components/flow-layout' },
          { text: 'FlowPanel ★', link: '/components/flow-panel' },
          { text: 'FolderTree ★', link: '/components/folder-tree' },
          { text: 'Footer ★', link: '/components/footer' },
          { text: 'FooterNav ★', link: '/components/footer-nav' },
          { text: 'FormGroup ★', link: '/components/form-group' },
          { text: 'FormItem ★', link: '/components/form-item' },
          { text: 'FormLayout ★', link: '/components/form-layout' },
          { text: 'FormTabs ★', link: '/components/form-tabs' },
          { text: 'FreeLayoutDrag ★', link: '/components/free-layout-drag' },
          { text: 'GaugeChart ★', link: '/components/gauge-chart' },
          { text: 'GbsAlarmModal ★', link: '/components/gbs-alarm-modal' },
          { text: 'GbsCascadePanel ★', link: '/components/gbs-cascade-panel' },
          { text: 'GbsDeviceTree ★', link: '/components/gbs-device-tree' },
          { text: 'GbsGatewayForm ★', link: '/components/gbs-gateway-form' },
          { text: 'GbsRegisterForm ★', link: '/components/gbs-register-form' },
          { text: 'GbsSignMonitor ★', link: '/components/gbs-sign-monitor' },
          { text: 'GbsStatusCard ★', link: '/components/gbs-status-card' },
          { text: 'GbsTimeSync ★', link: '/components/gbs-time-sync' },
          { text: 'GraphChart ★', link: '/components/graph-chart' },
          { text: 'GridLayoutDrag ★', link: '/components/grid-layout-drag' },
          { text: 'GroupNav ★', link: '/components/group-nav' },
          { text: 'Header ★', link: '/components/header' },
          { text: 'HeatMap ★', link: '/components/heat-map' },
          { text: 'Highlight ★', link: '/components/highlight' },
          { text: 'Icon ★', link: '/components/icon' },
          { text: 'ImageCrop ★', link: '/components/image-crop' },
          { text: 'ImageGroup ★', link: '/components/image-group' },
          { text: 'ImageUpload ★', link: '/components/image-upload' },
          { text: 'ImageViewer ★', link: '/components/image-viewer' },
          { text: 'IndexNav ★', link: '/components/index-nav' },
          { text: 'InfiniteScroll ★', link: '/components/infinite-scroll' },
          { text: 'InfoModal ★', link: '/components/info-modal' },
          { text: 'Ink404 ★', link: '/components/ink404' },
          { text: 'InputCaptcha ★', link: '/components/input-captcha' },
          { text: 'InputNumber ★', link: '/components/input-number' },
          { text: 'InputOTP ★', link: '/components/input-otp' },
          { text: 'LazyTree ★', link: '/components/lazy-tree' },
          { text: 'LineChart ★', link: '/components/line-chart' },
          { text: 'Link ★', link: '/components/link' },
          { text: 'Loading ★', link: '/components/loading' },
          { text: 'LoadingTip ★', link: '/components/loading-tip' },
          { text: 'LoginPanel ★', link: '/components/login-panel' },
          { text: 'Machine404 ★', link: '/components/machine404' },
          { text: 'Main ★', link: '/components/main' },
          { text: 'Mask ★', link: '/components/mask' },
          { text: 'MatrixCode ★', link: '/components/matrix-code' },
          { text: 'MdEditor ★', link: '/components/md-editor' },
          { text: 'Mention ★', link: '/components/mention' },
          { text: 'MenuBar ★', link: '/components/menu-bar' },
          { text: 'MergeTable ★', link: '/components/merge-table' },
          { text: 'Message ★', link: '/components/message' },
          { text: 'MiniNav ★', link: '/components/mini-nav' },
          { text: 'MonthPicker ★', link: '/components/month-picker' },
          { text: 'NoticeBar ★', link: '/components/notice-bar' },
          { text: 'Notification ★', link: '/components/notification' },
          { text: 'OcrScan ★', link: '/components/ocr-scan' },
          { text: 'OnvifAlarmPanel ★', link: '/components/onvif-alarm-panel' },
          { text: 'OnvifChannelManage ★', link: '/components/onvif-channel-manage' },
          { text: 'OnvifDeviceList ★', link: '/components/onvif-device-list' },
          { text: 'OnvifGroupTree ★', link: '/components/onvif-group-tree' },
          { text: 'OnvifRecordPlan ★', link: '/components/onvif-record-plan' },
          { text: 'OnvifSearch ★', link: '/components/onvif-search' },
          { text: 'OnvifSettingPanel ★', link: '/components/onvif-setting-panel' },
          { text: 'OnvifUrlForm ★', link: '/components/onvif-url-form' },
          { text: 'PTZControl ★', link: '/components/ptzcontrol' },
          { text: 'PageHeader ★', link: '/components/page-header' },
          { text: 'PagerNav ★', link: '/components/pager-nav' },
          { text: 'Password ★', link: '/components/password' },
          { text: 'PdfPreview ★', link: '/components/pdf-preview' },
          { text: 'PermissionPanel ★', link: '/components/permission-panel' },
          { text: 'PieChart ★', link: '/components/pie-chart' },
          { text: 'PivotTable ★', link: '/components/pivot-table' },
          { text: 'Pixel404 ★', link: '/components/pixel404' },
          { text: 'Plant404 ★', link: '/components/plant404' },
          { text: 'Popconfirm ★', link: '/components/popconfirm' },
          { text: 'Popover ★', link: '/components/popover' },
          { text: 'Preview ★', link: '/components/preview' },
          { text: 'Print ★', link: '/components/print' },
          { text: 'ProTable ★', link: '/components/pro-table' },
          { text: 'Progress ★', link: '/components/progress' },
          { text: 'ProgressTip ★', link: '/components/progress-tip' },
          { text: 'PropPanel ★', link: '/components/prop-panel' },
          { text: 'Qrcode ★', link: '/components/qrcode' },
          { text: 'QuarterPicker ★', link: '/components/quarter-picker' },
          { text: 'QuickNav ★', link: '/components/quick-nav' },
          { text: 'RadarChart ★', link: '/components/radar-chart' },
          { text: 'Radio ★', link: '/components/radio' },
          { text: 'RadioGroup ★', link: '/components/radio-group' },
          { text: 'RangeInput ★', link: '/components/range-input' },
          { text: 'Ranking ★', link: '/components/ranking' },
          { text: 'Rate ★', link: '/components/rate' },
          { text: 'ResizeBox ★', link: '/components/resize-box' },
          { text: 'Result ★', link: '/components/result' },
          { text: 'RichText ★', link: '/components/rich-text' },
          { text: 'RouterNav ★', link: '/components/router-nav' },
          { text: 'Row ★', link: '/components/row' },
          { text: 'ScaleLayout ★', link: '/components/scale-layout' },
          { text: 'SchemaRenderer ★', link: '/components/schema-renderer' },
          { text: 'ScrollNav ★', link: '/components/scroll-nav' },
          { text: 'ScrollNotice ★', link: '/components/scroll-notice' },
          { text: 'Scrollbar ★', link: '/components/scrollbar' },
          { text: 'Search ★', link: '/components/search' },
          { text: 'SearchFilterPanel ★', link: '/components/search-filter-panel' },
          { text: 'SelectNav ★', link: '/components/select-nav' },
          { text: 'SettingPanel ★', link: '/components/setting-panel' },
          { text: 'Sider ★', link: '/components/sider' },
          { text: 'Simple404 ★', link: '/components/simple404' },
          { text: 'Skeleton ★', link: '/components/skeleton' },
          { text: 'Slider ★', link: '/components/slider' },
          { text: 'SmsCode ★', link: '/components/sms-code' },
          { text: 'Space ★', link: '/components/space' },
          { text: 'Space404 ★', link: '/components/space404' },
          { text: 'Spacer ★', link: '/components/spacer' },
          { text: 'Spin ★', link: '/components/spin' },
          { text: 'Split ★', link: '/components/split' },
          { text: 'SplitVideoWall ★', link: '/components/split-video-wall' },
          { text: 'StackLayout ★', link: '/components/stack-layout' },
          { text: 'Statistic ★', link: '/components/statistic' },
          { text: 'StatusTip ★', link: '/components/status-tip' },
          { text: 'StepForm ★', link: '/components/step-form' },
          { text: 'StepItem ★', link: '/components/step-item' },
          { text: 'StepNav ★', link: '/components/step-nav' },
          { text: 'Steps ★', link: '/components/steps' },
          { text: 'StickyTable ★', link: '/components/sticky-table' },
          { text: 'SuccessModal ★', link: '/components/success-modal' },
          { text: 'TabPane ★', link: '/components/tab-pane' },
          { text: 'TableAction ★', link: '/components/table-action' },
          { text: 'TableDrag ★', link: '/components/table-drag' },
          { text: 'TableExport ★', link: '/components/table-export' },
          { text: 'TablePrint ★', link: '/components/table-print' },
          { text: 'TabsNav ★', link: '/components/tabs-nav' },
          { text: 'Tag ★', link: '/components/tag' },
          { text: 'TagInput ★', link: '/components/tag-input' },
          { text: 'Tech404 ★', link: '/components/tech404' },
          { text: 'TelemetryProvider ★', link: '/components/telemetry-provider' },
          { text: 'TemplateDrag ★', link: '/components/template-drag' },
          { text: 'TemplateSelect ★', link: '/components/template-select' },
          { text: 'Textarea ★', link: '/components/textarea' },
          { text: 'ThemeProvider ★', link: '/components/theme-provider' },
          { text: 'Thumbnail ★', link: '/components/thumbnail' },
          { text: 'TimePicker ★', link: '/components/time-picker' },
          { text: 'TimeRangeInput ★', link: '/components/time-range-input' },
          { text: 'TimeSelect ★', link: '/components/time-select' },
          { text: 'Timeline ★', link: '/components/timeline' },
          { text: 'TimelineItem ★', link: '/components/timeline-item' },
          { text: 'TimelineList ★', link: '/components/timeline-list' },
          { text: 'Toast ★', link: '/components/toast' },
          { text: 'Tooltip ★', link: '/components/tooltip' },
          { text: 'TopNav ★', link: '/components/top-nav' },
          { text: 'Transfer ★', link: '/components/transfer' },
          { text: 'TransferTree ★', link: '/components/transfer-tree' },
          { text: 'TreeChart ★', link: '/components/tree-chart' },
          { text: 'TreeForm ★', link: '/components/tree-form' },
          { text: 'TreeSelect ★', link: '/components/tree-select' },
          { text: 'TreeTable ★', link: '/components/tree-table' },
          { text: 'TreeTransfer ★', link: '/components/tree-transfer' },
          { text: 'Typography ★', link: '/components/typography' },
          { text: 'Upload ★', link: '/components/upload' },
          { text: 'UserInfoCard ★', link: '/components/user-info-card' },
          { text: 'VcrBackupTask ★', link: '/components/vcr-backup-task' },
          { text: 'VcrClipCut ★', link: '/components/vcr-clip-cut' },
          { text: 'VcrDownloadPanel ★', link: '/components/vcr-download-panel' },
          { text: 'VcrMarkPoint ★', link: '/components/vcr-mark-point' },
          { text: 'VcrSearchPanel ★', link: '/components/vcr-search-panel' },
          { text: 'VcrSpeedControl ★', link: '/components/vcr-speed-control' },
          { text: 'VcrStorageDashboard ★', link: '/components/vcr-storage-dashboard' },
          { text: 'VcrTimelinePlayer ★', link: '/components/vcr-timeline-player' },
          { text: 'VerticalStepNav ★', link: '/components/vertical-step-nav' },
          { text: 'VideoAdjust ★', link: '/components/video-adjust' },
          { text: 'VideoPlayer ★', link: '/components/video-player' },
          { text: 'VideoPreview ★', link: '/components/video-preview' },
          { text: 'VideoSnapshot ★', link: '/components/video-snapshot' },
          { text: 'VideoVolume ★', link: '/components/video-volume' },
          { text: 'VideoWatermark ★', link: '/components/video-watermark' },
          { text: 'VirtualTable ★', link: '/components/virtual-table' },
          { text: 'VirtualTree ★', link: '/components/virtual-tree' },
          { text: 'WarnModal ★', link: '/components/warn-modal' },
          { text: 'Waterfall ★', link: '/components/waterfall' },
          { text: 'Watermark ★', link: '/components/watermark' },
          { text: 'WeekPicker ★', link: '/components/week-picker' },
          { text: 'WordCloud ★', link: '/components/word-cloud' },
          { text: 'YearPicker ★', link: '/components/year-picker' }
        ]
      }
    ]
  }
})
