/**
 * Scan packages/components/{base,business} and regenerate barrel index.ts files.
 * Usage: npm run generate:entry
 */
import { readdirSync, writeFileSync, existsSync, statSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const baseDir = resolve(root, 'packages/components/base')
const bizDir = resolve(root, 'packages/components/business')

function dirsOf(parent) {
  if (!existsSync(parent)) return []
  return readdirSync(parent)
    .filter((name) => {
      const p = join(parent, name)
      return statSync(p).isDirectory() && !name.startsWith('.') && name !== 'node_modules'
    })
    .sort()
}

function genBase() {
  const names = dirsOf(baseDir)
  const lines = [
    '/** Base primitives only — forbidden to import business modules */',
    '/** AUTO-GENERATED by scripts/generate-entry.mjs — do not hand-edit */',
    ...names.map((n) => `export { default as ${n} } from './${n}'`)
  ]
  writeFileSync(resolve(baseDir, 'index.ts'), `${lines.join('\n')}\n`, 'utf8')
  console.log(`[generate:entry] base → ${names.length} components`)
}

function genBusiness() {
  const names = dirsOf(bizDir)
  const lines = [
    '/** Business modules — only depend on base / hooks / theme / utils */',
    '/** AUTO-GENERATED by scripts/generate-entry.mjs — do not hand-edit */',
    ...names.map((n) => `export * from './${n}'`)
  ]
  writeFileSync(resolve(bizDir, 'index.ts'), `${lines.join('\n')}\n`, 'utf8')
  console.log(`[generate:entry] business → ${names.length} modules`)
}

genBase()
genBusiness()
