/**
 * Scan component packages and regenerate barrel index.ts files.
 * Usage: npm run generate:entry
 */
import { writeFileSync, existsSync, readdirSync, statSync, mkdirSync, readFileSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  COMPONENT_PACKAGES,
  FOUNDATION_PACKAGES,
  listComponentsForPackage,
  SPECIAL_BARREL_EXPORTS,
  componentDirRel
} from './component-package-map.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const bizDir = resolve(root, 'packages/components/business')

function dirsOf(parent) {
  if (!existsSync(parent)) return []
  return readdirSync(parent)
    .filter((name) => {
      const p = join(parent, name)
      return statSync(p).isDirectory() && !name.startsWith('.') && name !== 'node_modules'
    })
    .sort()
}

/** Types that do not use the component name prefix but must be public. */
const PUBLIC_TYPE_ALLOWLIST = {
  DataTable: ['Column', 'RowKey', 'SortOrder'],
  Tree: ['TreeNode', 'TreeKey'],
  Select: ['SelectOption'],
  Cascader: ['CascaderOption'],
  Transfer: ['TransferItem'],
  Upload: ['UploadFile', 'UploadRawFile']
}

/** Avoid colliding with packages/types or shared root barrel names. */
const TYPE_EXPORT_DENYLIST = new Set([
  'IconProps',
  'LoadingProps',
  'NavItem',
  'BaseProps',
  'Size',
  'Severity'
])

function readExportedTypeNames(typesPath) {
  const src = readFileSync(typesPath, 'utf8')
  return [
    ...src.matchAll(/export\s+type\s+(\w+)/g),
    ...src.matchAll(/export\s+interface\s+(\w+)/g)
  ].map((m) => m[1])
}

function typeExportLines(name, pkg) {
  const dir = resolve(root, componentDirRel(name))
  const typesPath = join(dir, 'types.ts')
  if (!existsSync(typesPath)) return []
  const allow = new Set(PUBLIC_TYPE_ALLOWLIST[name] || [])
  const siblings = listComponentsForPackage(pkg).filter((n) => n !== name)
  const filtered = readExportedTypeNames(typesPath).filter((t) => {
    if (TYPE_EXPORT_DENYLIST.has(t)) return false
    if (allow.has(t)) return true
    if (!(t === name || t.startsWith(name))) return false
    // Prefer longer sibling prefix (DescriptionsItemProps belongs to DescriptionsItem, not Descriptions)
    const longerOwner = siblings.find(
      (sib) => sib.length > name.length && (t === sib || t.startsWith(sib))
    )
    return !longerOwner
  })
  if (!filtered.length) return []
  return [`export type { ${[...new Set(filtered)].join(', ')} } from './${name}/types'`]
}

function barrelLines(name, pkg) {
  if (SPECIAL_BARREL_EXPORTS[name]) {
    return [SPECIAL_BARREL_EXPORTS[name], ...typeExportLines(name, pkg)]
  }
  return [`export { default as ${name} } from './${name}'`, ...typeExportLines(name, pkg)]
}

function barrelLine(name, pkg) {
  return barrelLines(name, pkg).join('\n')
}

function genPackage(pkg) {
  const names = listComponentsForPackage(pkg)
  // Verify dirs exist
  for (const n of names) {
    const dir = resolve(root, componentDirRel(n))
    if (!existsSync(dir)) {
      console.warn(`[generate:entry] missing dir for ${pkg}/${n}: ${dir}`)
    }
  }

  if (pkg === 'lowcode') {
    const uiDir = resolve(root, 'packages/lowcode/ui')
    mkdirSync(uiDir, { recursive: true })
    const lines = [
      '/** Lowcode Vue UI cluster — AUTO-GENERATED by scripts/generate-entry.mjs */',
      ...names.map((n) => barrelLine(n, pkg))
    ]
    writeFileSync(resolve(uiDir, 'index.ts'), `${lines.join('\n')}\n`, 'utf8')
    console.log(`[generate:entry] lowcode/ui → ${names.length} components`)
    return
  }

  const pkgDir = resolve(root, 'packages/components', pkg)
  mkdirSync(pkgDir, { recursive: true })
  const header =
    pkg === 'core'
      ? '/** Core primitives — must not import industry packages (gb28181/onvif/media) */'
      : INDUSTRY_HEADER(pkg)
  const lines = [
    header,
    '/** AUTO-GENERATED by scripts/generate-entry.mjs — do not hand-edit */',
    ...names.map((n) => barrelLine(n, pkg))
  ]
  writeFileSync(resolve(pkgDir, 'index.ts'), `${lines.join('\n')}\n`, 'utf8')
  console.log(`[generate:entry] ${pkg} → ${names.length} components`)
}

function INDUSTRY_HEADER(pkg) {
  if (pkg === 'gb28181' || pkg === 'onvif' || pkg === 'media') {
    return `/** Industry package @amg-webui/${pkg} — opt-in; never imported by core */`
  }
  if (pkg === 'form' || pkg === 'data' || pkg === 'overlay') {
    return `/** Foundation @amg-webui/${pkg} — depends on core only (no industry) */`
  }
  return `/** @amg-webui/${pkg} — AUTO package barrel */`
}

function genLegacyBase() {
  const baseDir = resolve(root, 'packages/components/base')
  mkdirSync(baseDir, { recursive: true })
  const lines = [
    '/**',
    ' * @deprecated Import from `@amg-webui/core` instead.',
    ' * Legacy path `components/base` re-exports **core only** (hard cut — no industry/form/data shim).',
    ' */',
    "export * from '../core'",
    ''
  ]
  writeFileSync(resolve(baseDir, 'index.ts'), lines.join('\n'), 'utf8')
  console.log('[generate:entry] legacy components/base → re-export core only')
}

function genComponentsBarrel() {
  const lines = [
    '/** Foundation component packages + business — industry is opt-in via @amg-webui/{gb28181,onvif,media} */',
    ...FOUNDATION_PACKAGES.map((p) => `export * from './${p}'`),
    "export * from './business'",
    ''
  ]
  writeFileSync(resolve(root, 'packages/components/index.ts'), lines.join('\n'), 'utf8')
  console.log('[generate:entry] components/index → foundation + business')
}

function genBusiness() {
  const names = dirsOf(bizDir).filter((n) => n !== '_shared' && !n.startsWith('_'))
  const lines = [
    '/** Business modules — only depend on foundation / hooks / theme / utils */',
    '/** AUTO-GENERATED by scripts/generate-entry.mjs — do not hand-edit */',
    "export * from './_shared'",
    ...names.map((n) => `export * from './${n}'`)
  ]
  writeFileSync(resolve(bizDir, 'index.ts'), `${lines.join('\n')}\n`, 'utf8')
  console.log(`[generate:entry] business → ${names.length} modules (+ _shared)`)
}

for (const pkg of COMPONENT_PACKAGES) {
  genPackage(pkg)
}
genLegacyBase()
genComponentsBarrel()
genBusiness()
