import type { ThemeExportFormat, ThemeStudioDraft } from './types'
import { normalizeTokenMap } from './model'

function escapeScssString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

export function exportThemeCss(
  tokens: Record<string, string>,
  selector = ':root'
): string {
  const normalized = normalizeTokenMap(tokens)
  const decls = Object.entries(normalized)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n')
  if (!decls) return `${selector} {\n  /* no custom tokens */\n}`
  return `${selector} {\n${decls}\n}`
}

export function exportThemeScss(tokens: Record<string, string>): string {
  const normalized = normalizeTokenMap(tokens)
  const lines = Object.entries(normalized).map(
    ([key, value]) => `${key}: ${value};`
  )
  if (!lines.length) {
    return '// AMG Theme Studio — no custom tokens\n'
  }
  return [
    '// AMG Theme Studio — custom token overlay',
    '// Apply via @use or paste into design partial',
    ':root {',
    ...lines.map((l) => `  ${l}`),
    '}'
  ].join('\n')
}

export function exportThemeJson(draft: ThemeStudioDraft): string {
  return JSON.stringify(
    {
      name: draft.name,
      baseDesign: draft.baseDesign,
      scheme: draft.scheme,
      tokens: normalizeTokenMap(draft.tokens)
    },
    null,
    2
  )
}

export function exportThemeTs(draft: ThemeStudioDraft): string {
  const tokens = normalizeTokenMap(draft.tokens)
  const entries = Object.entries(tokens)
    .map(([key, value]) => `    '${key}': '${escapeScssString(value)}'`)
    .join(',\n')

  return [
    '/** Generated by AMG Theme Studio — do not edit by hand. */',
    "import type { DesignStyleName, ColorScheme } from 'amg-webui/theme/core'",
    '',
    'export interface CustomThemeBundle {',
    '  name: string',
    '  baseDesign: DesignStyleName',
    '  scheme: ColorScheme',
    '  tokens: Record<string, string>',
    '}',
    '',
    `export const theme: CustomThemeBundle = {`,
    `  name: '${escapeScssString(draft.name)}',`,
    `  baseDesign: '${draft.baseDesign}',`,
    `  scheme: '${draft.scheme}',`,
    '  tokens: {',
    entries || "    // no tokens",
    '  }',
    '}',
    '',
    'export default theme',
    ''
  ].join('\n')
}

export function exportTheme(format: ThemeExportFormat, draft: ThemeStudioDraft): string {
  switch (format) {
    case 'css':
      return exportThemeCss(draft.tokens, `[data-design="${draft.name}"]`)
    case 'scss':
      return exportThemeScss(draft.tokens)
    case 'json':
      return exportThemeJson(draft)
    case 'theme-ts':
      return exportThemeTs(draft)
    default:
      return exportThemeJson(draft)
  }
}

export function downloadThemeExport(
  format: ThemeExportFormat,
  draft: ThemeStudioDraft
): { filename: string; content: string; mime: string } {
  const content = exportTheme(format, draft)
  const ext =
    format === 'json'
      ? 'json'
      : format === 'theme-ts'
        ? 'ts'
        : format === 'scss'
          ? 'scss'
          : 'css'
  return {
    filename: `${draft.name}.${ext}`,
    content,
    mime: format === 'json' ? 'application/json' : 'text/plain'
  }
}
